language: node_js
node_js: 
   - "stable"
directories:
   - "node_modules"
services:
   - mysql
cache:
   - "node_modules"
before_script:
   - mysql -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY ''"
   - mysql -u root -e 'CREATE DATABASE backend;'
   - mysql -u root -e 'CREATE DATABASE test;'
   - mysql -u root -e 'SHOW DATABASES'
   - mysql -u root -e 'USE test'
   - mysql -u root < ./setup.sql
   - mysql -u root -e "GRANT ALL ON test.* TO 'test'@'localhost';" 
   - npm install
   - npm run test
env:
   - ENV: 'TEST'