language: node_js
node_js: 
   - "stable"
directories:
   - "node_modules"
services:
   - mysql
before_script:
   - mysql -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY '..test2019!'"
   - mysql -u root -e 'CREATE DATABASE backend;'
   - mysql -u root -e 'SHOW DATABASES'
   - mysql -u root -e "GRANT ALL ON backend.* TO 'test'@'localhost';" 
   - npm install
env:
   - ENV: 'TEST'